### ISSUE TITLE
ModuleNotFoundError: No module named 'nnunet.network_architecture.torch_nn'

### ISSUE THREAD

**Issue by OldSixOne** [PengchengShi1220/NexToU#1]
I didn't find this on nnunet。
ModuleNotFoundError: No module named 'nnunet.network_architecture.torch_nn'

**Comment by PengchengShi1220** [comment]
Thank you for your interest in our project. I am pleased to inform you that we have uploaded the necessary files, including torch_nn.py, torch_edge.py, and pos_embed.py, to [network_architecture](https://github.com/PengchengShi1220/NexToU/tree/main/network_architecture), as well as nnUNetTrainerV2_nextou_bti_synapse.py and other files to [network_training](https://github.com/PengchengShi1220/NexToU/tree/main/network_training).

**Comment by PengchengShi1220** [comment]
> I didn't find this on nnunet。 ModuleNotFoundError: No module named 'nnunet.network_architecture.torch_nn'
Thank you for your interest in our project. I am pleased to inform you that we have uploaded the necessary files, including torch_nn.py, torch_edge.py, and pos_embed.py to [network_architecture](https://github.com/PengchengShi1220/NexToU/tree/main/network_architecture), as well as nnUNetTrainerV2_nextou_bti_synapse.py and other files to [network_training](https://github.com/PengchengShi1220/NexToU/tree/main/network_training).
