### ISSUE TITLE
Get demo run

### ISSUE THREAD

**Issue by OldSixOne** [PengchengShi1220/NexToU#2]
Can you provide an example of a demo or provide some relevant information.

**Comment by PengchengShi1220** [comment]
Thank you for your inquiry. We are in the process of creating a demo that showcases our training methods and will be uploading it soon. Stay tuned for updates!

**Comment by OldSixOne** [comment]
I want to do a quick answer test on my end, using pre processed data from nnunet, but an error was reported.

**Comment by PengchengShi1220** [comment]
Please check the updated NexToU installation and running demo that might help you with the error you encountered.
