### ISSUE TITLE
Access to the ICA dataset

### ISSUE THREAD

**Issue by JdbermeoUZH** [PengchengShi1220/NexToU#5]
Hello,

I was wondering if you were perhaps planning on making the ICA annotations of the OASIS-3 scans publicly available. 

I am working on test time adaptation for segmentation, and having access to a labeled ICA dataset would be a great help.

Best regards,

Juan

**Comment by PengchengShi1220** [comment]
Hi Juan,

Thank you for your interest. Unfortunately, we’re not able to make the ICA annotations of the OASIS-3 scans publicly available at this time. For the time being, I would recommend testing your methods on the dataset provided by [TopCoW2023](https://topcow23.grand-challenge.org/topcow23/). It also focuses on multi-class segmentation tasks on cerebral vasculature.

Best regards,
Pengcheng

**Comment by JdbermeoUZH** [comment]
Hi Pengcheng,

I understand, thanks for the information on the TopCoW challenge!

Best,

Juan
