### ISSUE TITLE
About training others datasets

### ISSUE THREAD

**Issue by sonwe1e** [PengchengShi1220/NexToU#8]
您好，您的代码和方法都很棒，我想尝试复现你的代码，但我遇到了这个报错，请问应该如何了解怎么解决这个问题

Traceback (most recent call last):
  File "/home/yhwu/miniconda3/envs/sw/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/yhwu/sw/nnUNet/nnunetv2/run/run_training.py", line 409, in run_training_entry
    run_training(
  File "/home/yhwu/sw/nnUNet/nnunetv2/run/run_training.py", line 282, in run_training
    nnunet_trainer.run_training()
  File "/home/yhwu/sw/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1280, in run_training
    self.on_train_start()
  File "/home/yhwu/sw/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 823, in on_train_start
    self.initialize()
  File "/home/yhwu/sw/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 207, in initialize
    self.network = self.build_network_architecture(
  File "/home/yhwu/sw/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer_nextou.py", line 43, in build_network_architecture
    num_stages = len(configuration_manager.conv_kernel_sizes)
AttributeError: 'list' object has no attribute 'conv_kernel_sizes'

**Comment by PengchengShi1220** [comment]
Hello @sonwe1e ,

Thank you for the message. The error appears to be connected to `configuration_manager`. This often happens when `configuration_manager` is not correctly set up or used, which is vital for elements like `conv_kernel_sizes`.

Configurations rely on `nnUNetPlans.json`. Please add this line in the code and share the output:

```python
print("configuration_manager: ", configuration_manager)
```

你好，

感谢你的留言。这个错误似乎与configuration_manager有关。通常，这种问题发生在configuration_manager没有正确设置或使用时，这对于定义如conv_kernel_sizes之类的元素至关重要。

配置依赖于nnUNetPlans.json。请在代码中添加以下这行并分享输出结果：
```python
print("configuration_manager: ", configuration_manager)
```

**Comment by sonwe1e** [comment]
十分感谢你的回复，为了能够复现你能工作，我做了以下的事情
首先，我把 github 上的代码都 clone 了下来并且按照教程把这些代码替换掉 nnUNet 本身的文件，并且 pip install -e .，然后在执行文件的时候出现了
Traceback (most recent call last):
  File "/home/yhwu/miniconda3/envs/sw/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/yhwu/sw/nnUNet/nnunetv2/run/run_training.py", line 409, in run_training_entry
    run_training(
  File "/home/yhwu/sw/nnUNet/nnunetv2/run/run_training.py", line 282, in run_training
    nnunet_trainer.run_training()
  File "/home/yhwu/sw/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1768, in run_training
    self.on_train_start()
  File "/home/yhwu/sw/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1152, in on_train_start
    self.initialize()
  File "/home/yhwu/sw/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 301, in initialize
    self.network = self.build_network_architecture(
TypeError: nnUNetTrainer_NexToU.build_network_architecture() takes from 4 to 5 positional arguments but 6 were given
为了解决这个错误，我将 def initialize(self): 进行了修改
<img width="615" alt="image" src="https://github.com/PengchengShi1220/NexToU/assets/72198365/e0362881-8688-468f-95c5-d427a8ca3b49">
修改后，出现了不存在 conv_kernel_size 的报错，我认为是 nnUNetPlans.json 的问题，我将 github 中的 3d_fullres 的配置对我本身文件的内容进行了替换，并保证是包含这个配置的
<img width="393" alt="image" src="https://github.com/PengchengShi1220/NexToU/assets/72198365/7fe993e3-4fef-4340-820b-8afab1405f3d">
但我发现在经过 nnUNetTrainer 这个类的 init 部分后，conv_kernel_size 会变成 kernel_size，这是我目前无法解决的地方
<img width="753" alt="image" src="https://github.com/PengchengShi1220/NexToU/assets/72198365/aa24c4a0-30ff-40ec-8eb5-e1ff178c76e5">

我在尽我最大的努力避免为了一些简单的问题麻烦你，但目前我无法解决这个问题，所以希望你能帮助我

**Comment by PengchengShi1220** [comment]
Hello，

Please be careful not to replace the existing `nnUNetTrainer.py` file. You should only copy the file, avoiding replacement of the original content. The specific operation is as follows:

```
cp NexToU-NexToU_nnunetv2/nnUNetTrainer/* nnUNet-2.0/nnunetv2/training/nnUNetTrainer/
```

Additionally, ensure that the version of nnUNetV2 you download is the v2.0 version, as nnUNetV2 is continuously being updated, and newer versions may not be compatible.
```
wget https://github.com/MIC-DKFZ/nnUNet/archive/refs/tags/v2.0.tar.gz
```

If you have any questions or need further assistance, feel free to reply.



你好，

请注意不要替换原有的 `nnUNetTrainer.py` 文件。你应该只复制文件，避免替换原有内容。具体操作如下：

```
cp NexToU-NexToU_nnunetv2/nnUNetTrainer/* nnUNet-2.0/nnunetv2/training/nnUNetTrainer/
```

此外，确保你下载的nnUNetV2版本是 v2.0 version，因为nnUNetV2一直在更新，新版本可能会不适配。
```
wget https://github.com/MIC-DKFZ/nnUNet/archive/refs/tags/v2.0.tar.gz
```

如果有任何疑问或需要进一步的帮助，请随时回复。

**Comment by sonwe1e** [comment]
可我是严格按照 readme 上的内容执行的，我并没有替换掉 nnUNet 本身的文件，并且我是几天前才下载的 nnUNetv2

**Comment by PengchengShi1220** [comment]
我注意到你提供的nnUNetTrainer.py的截图，你的nnUNetV2版本不是2.0的版本，请通过下面的链接下载：

```
wget https://github.com/MIC-DKFZ/nnUNet/archive/refs/tags/v2.0.tar.gz
```

新版本里面的self.build_network_architecture的输入参数发生了改变。

**Comment by sonwe1e** [comment]
感谢你的耐心回复，我的 nnUNet 代码是通过 github 的 git clone 得到的，和 wget 的版本不一样，我通过 wget 版本实现了方法的复现，再次谢谢你的耐心
![image](https://github.com/PengchengShi1220/NexToU/assets/72198365/f03dbb00-d896-45be-be84-01e2bc0a4369)

**Comment by PengchengShi1220** [comment]
I'm glad to hear that you've successfully replicated the method. If you have any further questions, feel free to ask.

很高兴听到你已经成功地复现了方法。如果你还有任何疑问，欢迎继续提问。

**Comment by sonwe1e** [comment]
你好，我对 TopCoW 这个比赛十分感兴趣，我完成了对数据集的下载，目前遇到了一些问题，想请教一些问题
第一个问题是我看到 TopCoW 的 MultiClass 的数据标签从 12 到了 15，中间缺失了 13 和 14，请问你是如何处理这个问题的，如果可以的话能看看你比赛的 nnUNetPlans 吗
第二个问题是我在运行过程中出现了一个 Warning，具体如下，请问在你运行代码的过程中也会出现这个问题吗
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
期待你的答复，谢谢

**Comment by PengchengShi1220** [comment]
Hello,

1. Regarding your first question about handling data labels, you can change the value of 15 (i.e., A2 in the third segment, 3rd-A2) to 13 for model training purposes. For the specific file `nnUNetPlans.json` in TopCoW training, you can refer to [nnUNetPlans.json](https://github.com/PengchengShi1220/NexToU/files/14664140/nnUNetPlans.json).

2. As for your second question, the `TracerWarning` you mentioned is a common warning related to the versions of Python or PyTorch. This warning usually does not affect model training.

I hope these answers help you resolve your issues.


你好，

1. 对于第一个问题，关于数据标签的处理，你可以将15值（即第三段的A2, 3rd-A2）修改为13，以用于模型训练。关于TopCoW训练的`nnUNetPlans.json`具体文件，你可以参考
[nnUNetPlans.json](https://github.com/PengchengShi1220/NexToU/files/14664140/nnUNetPlans.json)

2. 对于第二个问题，您提到的`TracerWarning`是一个常见的警告，它与Python或PyTorch的版本有关。这个警告对模型训练通常没有影响。

希望这些回答能帮助你解决问题。

**Comment by sonwe1e** [comment]
抱歉再次打扰你，代码已经成功复现了，运行的效果很好，如果可以的话，我想查看你在 TopCoW 比赛中验证集的输出结果，和我复现的结果做一下比对，谢谢
Sorry to bother you again, the code has been successfully reproduced and is running well, if possible I'd like to see the output of your validation set from the TopCoW competition and compare it to my reproduction, thanks!

**Comment by PengchengShi1220** [comment]
Hello, 

I'm glad to hear that you have successfully reproduced. I utilized 72 out of 90 cases from TopCoW 2023 MRA dataset as the training set and the remaining 18 cases as the validation set, corresponding to fold 0 in nnUNet framework. Training was performed using nnUNetTrainer_NexToU_noMirroring. Relevant files, including `nnUNetPlans.json` and `splits_final.json`, can be found at these links: [nnUNetPlans.json](https://github.com/PengchengShi1220/NexToU/files/14725627/nnUNetPlans.json) and [splits_final.json](https://github.com/PengchengShi1220/NexToU/files/14725628/splits_final.json). For reference, the training log of the first 30 epochs is available at [training_log_2024_3_22_23_06_18.txt](https://github.com/PengchengShi1220/NexToU/files/14725656/training_log_2024_3_22_23_06_18.txt).


你好，

很高兴听到你已经成功复现。我使用了TopCoW 2023 MRA数据集90例中的72例作为训练集，剩余18例作为验证集，对应于nnUNet框架中的fold 0。训练使用的是nnUNetTrainer_NexToU_noMirroring。相关文件包括`nnUNetPlans.json`和`splits_final.json`，可以在以下链接中找到：[nnUNetPlans.json](https://github.com/PengchengShi1220/NexToU/files/14725627/nnUNetPlans.json) 和 [splits_final.json](https://github.com/PengchengShi1220/NexToU/files/14725628/splits_final.json)。作为参考，前30个epoch的训练log可在此处查看 [training_log_2024_3_22_23_06_18.txt](https://github.com/PengchengShi1220/NexToU/files/14725656/training_log_2024_3_22_23_06_18.txt)。

**Comment by PengchengShi1220** [comment]
Hello! You can find the weight files for NexToU v1.0 (based on nnU-Net v2.0) from the TopCoW 2023 MRA training at this Google Drive link: [TopCoW 2023 MRA Weights](https://drive.google.com/drive/folders/1VcH00e-4KgVUOJUJckZEChD0RWwLRyW6?usp=sharing).

**Comment by sonwe1e** [comment]
I’m deeply grateful for your assistance. Thank you. ❤️
